### ISSUE TITLE
Add auto-changelog gesture

### ISSUE THREAD

**Issue by Debaerdm** [AxaGuilDEv/Skizzle#21]
# Issue Template
## Summary
See auto-changelog dependency

**Comment by bernard-arnaud** [comment]
We've implemented auto-changelog in one of our projects.
We created a npm command that we run inside a script during the CI, that looks like this : 

```
npm version $(Build.SourceBranchName)
git checkout $(ReleaseBranchName)
npm run changelog
git add CHANGELOG.md
git add package.json
git add package-lock.json
git commit -m "build: bump version to $(Build.SourceBranchName) with changelog"
git push origin
git push --tags
```

npm version handles the bumping of version in package.json and creates a corresponding git tag, that's why we're pushing them.
Is this something similar to what you'd like ?
